[package]
name = "brightnesscontrol"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
hash = "0.3.0"
maplit = "1.0.2"
regex = "1.10.4"
serde = "1.0.197"
serde_json = "1.0.115"
utils = { version = "0.1.0", path = "../utils" }
